# Generated by Django 2.2.7 on 2019-12-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markerplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='ends_at',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='ends_at'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.TextField(default='', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='internal_comment',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='internal_comment'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='is_shipping_free',
            field=models.CharField(default='', max_length=20, verbose_name='is_shipping_free'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='nb_messages',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='nb_messages'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_fnac_id',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='offer_fnac_id'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_seller_id',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='offer_seller_id'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='pro_price',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='pro_price'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='product_fnac_id',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='product_fnac_id'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='product_name',
            field=models.TextField(default='', null=True, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='product_state',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='product_state'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='product_url',
            field=models.TextField(default='', null=True, verbose_name='product_url'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='promotion',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='promotion'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='quantity',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='showcase',
            field=models.CharField(default='', max_length=20, verbose_name='showcase'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='starts_at',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='starts_at'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='trigger_customer_type',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='trigger_customer_type'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='type_label',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='type_label'),
        ),
    ]
