# Generated by Django 2.2.7 on 2020-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='OfferOrder',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('offer', models.CharField(max_length=10, verbose_name='offer')),
                ('order', models.CharField(max_length=10, verbose_name='order')),
                ('message', models.CharField(max_length=10, verbose_name='message')),
                ('incident', models.CharField(max_length=10, verbose_name='incident')),
            ],
            options={
                'db_table': 'offer_order_message_incident_num',
            },
        ),
    ]
