# Generated by Django 2.2.7 on 2019-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('user', models.CharField(max_length=20, verbose_name='user')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
